version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - VITE_API_URL=http://167.86.125.48:8045
    restart: unless-stopped

  # Backend servisiniz varsa buraya ekleyebilirsiniz
  # backend:
  #   build: ../backend
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - DB_HOST=db
  #     - DB_USER=user
  #     - DB_PASS=password
  #   depends_on:
  #     - db

  # Veritabanı servisiniz varsa buraya ekleyebilirsiniz
  # db:
  #   image: postgres:14-alpine
  #   environment:
  #     - POSTGRES_USER=user
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_DB=taskdb
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
# volumes:
#   postgres_data:
